#!/bin/sh

NUM_JBOOST_JAR=`echo "${CLASSPATH}" | sed 's/:/\n/g' | grep 'jboost\.jar'  | wc -l`
if [ $NUM_JBOOST_JAR -eq 0 ]; then
    echo "You do not have your CLASSPATH variable set correctly."
    echo "You have the following dirs in your java path:"
    echo "$CLASSPATH" | sed 's/:/\n/g' | sed 's/^[ \t]*//' | sed '/^$/d' | sed 's/^/\t/g'
    echo "If jboost.jar doesn't exist, downloaded the distribution again."
    echo "To set CLASSPATH, run \"source setClasspath.sh\""
    exit 1
fi

echo -n "JBoost jar file is: "
echo "${CLASSPATH}" | sed 's/:/\n/g' | grep 'jboost\.jar'

exec java -Xmx500M jboost.controller.Controller $@

if [ $? -ne 0 ]; then
    echo "JBoost could not run, please see above errors."
fi

exit $?
